scripts improvements (shellcheck)

diff --git a/tools/clone b/tools/clone
--- a/tools/clone
+++ b/tools/clone
@@ -1,30 +1,28 @@
 #!/bin/sh
 
 error() {
-    echo>&2 $1
-    exit 1
+	echo>&2 "${1}"
+	exit 1
 }
 
-rmlist="tools Dockerfile clone update .git"
+[ $# -ne 1 ] && error "Usage: ${0} ProjectName\nUsage: ${0} ProjectDirectory";
+_dname=${1}
+[ "$(echo "${1}"|tr -dc /|wc -c)" -eq 0 ] && _dname=../${1}
+dname=$(readlink -f "${_dname}")
+[ -d "${dname}" ] && error "Error: directory ${dname} already exists"
 
-[ $# -ne 1 ] && error "Usage: $0 ProjectName\nUsage: $0 ProjectDirectory";
-_dname=$1
-[ $(echo $1|tr -dc /|wc -c) -eq 0 ] && _dname=../$1
-dname=$(readlink -f $_dname)
-[ -d "$dname" ] && error "Error: directory $dname already exists"
+mkdir -p "${dname}" || error "Error: cannot create ${dname}"
+cp -rf mbed "${dname}/"
+cp -rf src "${dname}/"
+cp Makefile "${dname}/"
+cp .targets.mk "${dname}/"
+cp Doxyfile "${dname}/"
+cp .gitignore "${dname}/"
+cp CMakeLists.txt "${dname}/"
+cp size_info "${dname}/"
+cp targets.cmake "${dname}/"
+mkdir "${dname}/inc" "${dname}/lib"
 
-mkdir -p $dname || error "Error: cannot create $dname"
-cp -rf mbed $dname/
-cp -rf src $dname/
-cp Makefile $dname/
-cp .targets.mk $dname/
-cp Doxyfile $dname/
-cp .gitignore $dname/
-cp CMakeLists.txt $dname/
-cp size_info $dname/
-cp targets.cmake $dname/
-mkdir $dname/inc $dname/lib
-
-echo "Info: project created in $dname"
+echo "Info: project created in ${dname}"
 
 exit 0
diff --git a/tools/full-update b/tools/full-update
--- a/tools/full-update
+++ b/tools/full-update
@@ -1,14 +1,14 @@
 #!/bin/sh
 
 error() {
-    echo>&2 $1
-    exit 1
+	echo>&2 "${1}"
+	exit 1
 }
 
 warning() {
-    opt=
-    [ "$1" = '-n' ] && opt='-n' && shift
-    echo $opt '\033[1m\033[33m'$*'\033[0m'
+	opt=
+	[ "${1}" = '-n' ] && opt='-n' && shift
+	echo "${opt}" '\033[1m\033[33m'$*'\033[0m'
 }
 
 uddocker=n
@@ -18,30 +18,30 @@ warning "It will also try to remove ALL unnecessary files. It can be uncomplete.
 warning "By doing this, there is no warranty your files will be safe"
 warning "Please, make a backup (e.g. git stash) before continuing"
 warning -n "Continue anyway? [y/N] "
-read ask
-[ "$ask" != y ] && error quit
+read -r ask
+[ "${ask}" != y ] && error quit
 
 if [ $# -eq 0 ]; then
-    echo -n "Update Docker? [Y/n] "
-    read uddocker
+	echo -n "Update Docker? [Y/n] "
+	read -r uddocker
 
-    echo -n "Type a list of projects to update: "
-    read projects
+	echo -n "Type a list of projects to update: "
+	read -r projects
 else
-    projects=$*
+	projects=$*
 fi
 
-[ "$uddocker" != n ] && docker build --rm -t nucleo .
+[ "${uddocker}" != n ] && docker build --rm -t nucleo .
 
-for project in $projects; do 
-    dname=$project
-    [ ! -d "$project" ] && dname=../$project
-    [ ! -d "$dname" ] && error "Error: project $project not found"
+for project in ${projects}; do
+	dname=${project}
+	[ ! -d "${project}" ] && dname=../${project}
+	[ ! -d "${dname}" ] && error "Error: project ${project} not found"
 
-    make -C $dname purge
-    rm -rf $dname/mbed $dname/.mk 
-		cp -rf mbed $dname/
-    cp -f Makefile $dname/
-		cp -f .targets.mk $dname/
+	make -C "${dname}" purge
+	rm -rf "${dname}/mbed" "${dname}/.mk "
+	cp -rf mbed "${dname}/"
+	cp -f Makefile "${dname}/"
+	cp -f .targets.mk "${dname}/"
 done
 exit 0
diff --git a/tools/update b/tools/update
--- a/tools/update
+++ b/tools/update
@@ -1,33 +1,33 @@
 #!/bin/sh
 
 error() {
-    echo>&2 $1
-    exit 1
+	echo>&2 "$1"
+	exit 1
 }
 
 uddocker=n
 
-if [ $# -eq 0 ]; then
-    echo -n "Update Docker? [Y/n] "
-    read uddocker
+if [ "$#" -eq 0 ]; then
+	echo -n "Update Docker? [Y/n] "
+	read -r uddocker
 
-    echo -n "Type a list of projects to update: "
-    read projects
+	echo -n "Type a list of projects to update: "
+	read -r projects
 else
-    projects=$*
+	projects=$*
 fi
 
-[ "$uddocker" != n ] && docker build --rm -t nucleo .
+[ "${uddocker}" != n ] && docker build --rm -t nucleo .
 
-for project in $projects; do 
-    dname=$project
-    [ ! -d "$project" ] && dname=../$project
-    [ ! -d "$dname" ] && error "Error: project $project not found"
+for project in ${projects}; do
+	dname=${project}
+	[ ! -d "${project}" ] && dname=../${project}
+	[ ! -d "${dname}" ] && error "Error: project ${project} not found"
 
-    make -C $dname purge
-    rm -rf $dname/mbed $dname/.targets.mk
-    cp -rf mbed $dname/
-    cp -f .targets.mk $dname/
+	make -C "${dname}" purge
+	rm -rf "${dname}/mbed" "${dname}/.targets.mk"
+	cp -rf mbed "${dname}/"
+	cp -f .targets.mk "${dname}/"
 done
 
 echo "Warning: main makefile not updated! Think about checking out new version"
